apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
    - name: metrics
      protocol: TCP
      port: 8080         
      targetPort: 8080