apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.databaseUrl }}"
