CREATE TABLE IF NOT EXISTS users (
  id          BIGSERIAL PRIMARY KEY,
  email       TEXT UNIQUE NOT NULL,
  password    TEXT NOT NULL,
	created_at  TIMESTAMP WITHOUT TIME ZONE,
	updated_at  TIMESTAMP WITHOUT TIME ZONE,
	deleted_at  TIMESTAMP WITHOUT TIME ZONE
);

CREATE UNIQUE INDEX idx_users_email ON users (email);